name: sync-postman-collections

on: [push]
#  push:
#    branches:
#      - develop

jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-20.04
    steps:
      - name: cancel running workflows
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  sync_core_collection:
    name: Sync Postman Core collection w/ latest develop
    environment: Postman
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Postman credentials
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: .env
          contents: POSTMAN_API_KEY=${{ secrets.POSTMAN_API_TOKEN }}
          write-mode: overwrite
      - name: Checkout core repo
        uses: actions/checkout@v2
        with:
          repository: radixdlt/radixdlt
          path: core
      - name: Change OpenApi version in the Core API spec
        run: sed -i 's/3.1.0/3.0.0/' core/radixdlt-core/radixdlt/src/main/java/com/radixdlt/api/core/api.yaml
      - name: Create Portman configuration for Core API
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: cliopts.json
          contents: '{"postmanWorkspaceName":"Team Workspace"}'
          write-mode: overwrite
      - name: Replace hardcoded values with variables
        run: |
          sed -i 's/mainnet/"{{network}}"/g' core/radixdlt-core/radixdlt/src/main/java/com/radixdlt/api/core/api.yaml
      - name: Update Postman's Core API collection from the spec
        run: |
          npx @apideck/portman -l core/radixdlt-core/radixdlt/src/main/java/com/radixdlt/api/core/api.yaml \
            --postmanUid 14449947-fb9a194f-6341-41d7-a826-8c701f0fbf57 \
            --syncPostman true --envFile .env --cliOptionsFile cliopts.json
      - name: Download the collection
        run: |
          curl -X GET -H "X-API-KEY:${{secrets.POSTMAN_API_TOKEN}}" https://api.getpostman.com/collections/14449947-fb9a194f-6341-41d7-a826-8c701f0fbf57 > tmp.core.collection.json
      - name: Add a timestamp to the name
        run: |
          sed -i 's/"name":".*","description":"This API/"name":"Core API (develop) ${{steps.date.outputs.date}} UTC","description":"This API/' tmp.core.collection.json
      - name: Change the baseUrl variable name
        run: |
          sed -i 's/{{baseUrl}}/{{coreBaseUrl}}/g' tmp.core.collection.json
      - name: Update the collection
        run: |
          curl -X PUT -H "X-API-KEY:${{secrets.POSTMAN_API_TOKEN}}" -H "Content-Type: application/json" \
             https://api.getpostman.com/collections/14449947-fb9a194f-6341-41d7-a826-8c701f0fbf57 --data "@tmp.core.collection.json"

#      - name: Create Portman configuration for System API
#        uses: DamianReeves/write-file-action@v1.0
#        with:
#          path: cliopts.json
#          contents: '{"postmanWorkspaceName":"Team Workspace"}'
#          write-mode: overwrite
#      - name: Generate and upload Postman's System API collection
#        run: |
#          npx @apideck/portman -l core/radixdlt-core/radixdlt/src/main/java/com/radixdlt/api/system/api.yaml \
#            --postmanUid 14449947-cbede7fb-7361-4d91-becc-e1e10e0b2454 \
#            --syncPostman true --envFile .env --cliOptionsFile cliopts.json